#!/bin/zsh

# undecorated NotesAndRests only
echo "musicdiff --include notesandrests"
python -m musicdiff --output text --include notesandrests -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# undecorated NotesAndRests plus Barlines
echo "musicdiff --include notesandrests barlines"
python -m musicdiff --output text --include notesandrests barlines -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# undecorated NotesAndRests plus Barlines and Directions
echo "musicdiff --include notesandrests barlines directions"
python -m musicdiff --output text --include notesandrests barlines directions -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# undecorated NotesAndRests plus Barlines and Directions, minus Barlines
echo "musicdiff --include notesandrests barlines directions --exclude barlines"
python -m musicdiff --output text --include notesandrests barlines directions --exclude barlines -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests only
echo "musicdiff --include decoratednotesandrests"
python -m musicdiff --output text --include decoratednotesandrests -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests excluding ties
echo "musicdiff --include decoratednotesandrests --exclude ties"
python -m musicdiff --output text --include decoratednotesandrests --exclude ties -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests excluding beams and ties
echo "musicdiff --include decoratednotesandrests --exclude beams ties"
python -m musicdiff --output text --include decoratednotesandrests --exclude beams ties -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests excluding beams and ties and slurs
echo "musicdiff --include decoratednotesandrests --exclude beams ties slurs"
python -m musicdiff --output text --include decoratednotesandrests --exclude beams ties slurs -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests with Voicing
echo "musicdiff -i decoratednotesandrests voicing"
python -m musicdiff -o text -i decoratednotesandrests voicing -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests with Lyrics
echo "musicdiff -i decoratednotesandrests lyrics"
python -m musicdiff --output t -i decoratednotesandrests lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests with Lyrics and Voicing
echo "musicdiff -i decoratednotesandrests voicing lyrics"
python -m musicdiff --output t -i decoratednotesandrests voicing lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# OtherObjects only
echo "musicdiff -i otherobjects"
python -m musicdiff -o t -i otherobjects -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# OtherObjects with Style
echo "musicdiff -i otherobjects style"
python -m musicdiff -o t -i otherobjects style -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects (same as AllObjects)
echo "musicdiff -i decoratednotesandrests otherobjects"
python -m musicdiff -o t -i decoratednotesandrests otherobjects -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, no Lyrics
echo "musicdiff -i decoratednotesandrests otherobjects -x lyrics"
python -m musicdiff -o t -i decoratednotesandrests otherobjects -x lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, no Lyrics, no Barlines
echo "musicdiff -i decoratednotesandrests otherobjects -x lyrics barlines"
python -m musicdiff -o t -i decoratednotesandrests otherobjects -x lyrics barlines -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# AllObjects (same as DecoratedNotesAndRests, OtherObjects)
echo "musicdiff -i allobjects"
python -m musicdiff -o t -i allobjects -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, Style
echo "musicdiff -i decoratednotesandrests otherobjects style"
python -m musicdiff -o t -i decoratednotesandrests otherobjects style -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, Style, no Lyrics
echo "musicdiff -i decoratednotesandrests otherobjects style -x lyrics"
python -m musicdiff -o t -i decoratednotesandrests otherobjects style -x lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# AllObjects | Style (same as DecoratedNotesAndRests, OtherObjects, Style)
echo "musicdiff -i allobjects style"
python -m musicdiff -o t -i allobjects style -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# Metadata only
echo "musicdiff -i metadata"
python -m musicdiff -o t -i metadata -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# Everything except Voicing
echo "musicdiff -i allobjects style metadata"
python -m musicdiff -o t -i allobjects style metadata -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei
