#!/bin/zsh

mode=runtests
fails=0

run_musicdiff() {
    name=$1
    shift 1
    if [[ "${mode}" == "makeresults" ]]; then
        python -m musicdiff --output text $@ -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei > tests/test_results/cmd_line_results_$name.txt >& /dev/null
    else
        python -m musicdiff --output text $@ -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei > /tmp/results.txt >& /dev/null
        diff -q /tmp/results.txt tests/test_results/cmd_line_results_$name.txt >/dev/null 2>&1
        if [[ $? -ne 0 ]]; then
            print "Test failure: musicdiff $@"
            ((fails+=1))
        else
            print "Test success: musicdiff $@"
        fi
    fi
}

# simple includes (and some simple excludes that just remove something we included)
run_musicdiff notesandrests --include notesandrests
run_musicdiff notesandrests_barlines -i notesandrests barlines
run_musicdiff notesandrests_barlines -i notesandrests barlines directions -x directions
run_musicdiff notesandrests_barlines -i notesandrests barlines voicing -x voicing
run_musicdiff notesandrests_barlines -i notesandrests barlines metadata -x metadata
run_musicdiff notesandrests_barlines_directions -i notesandrests barlines directions
run_musicdiff notesandrests_directions -i notesandrests barlines directions -x barlines

# simple includes (notesandrests barlines) + combo include (otherobjects), then exclude
# otherobjects (which removes barlines, too), leaving notesandrests
run_musicdiff notesandrests -i notesandrests barlines otherobjects style -x style otherobjects

# combo include: decoratednotesandrests
run_musicdiff decoratednotesandrests --include decoratednotesandrests
print Total failures: ${fails}
exit ${fails}

#
# DecoratedNotesAndRests excluding ties
echo "musicdiff --include decoratednotesandrests --exclude ties"
python -m musicdiff --output text --include decoratednotesandrests --exclude ties -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests excluding beams and ties
echo "musicdiff --include decoratednotesandrests --exclude beams ties"
python -m musicdiff --output text --include decoratednotesandrests --exclude beams ties -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests excluding beams and ties and slurs
echo "musicdiff --include decoratednotesandrests --exclude beams ties slurs"
python -m musicdiff --output text --include decoratednotesandrests --exclude beams ties slurs -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests with Voicing
echo "musicdiff -i decoratednotesandrests voicing"
python -m musicdiff -o text -i decoratednotesandrests voicing -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests with Lyrics
echo "musicdiff -i decoratednotesandrests lyrics"
python -m musicdiff --output t -i decoratednotesandrests lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests with Lyrics and Voicing
echo "musicdiff -i decoratednotesandrests voicing lyrics"
python -m musicdiff --output t -i decoratednotesandrests voicing lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# OtherObjects only
echo "musicdiff -i otherobjects"
python -m musicdiff -o t -i otherobjects -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# OtherObjects with Style
echo "musicdiff -i otherobjects style"
python -m musicdiff -o t -i otherobjects style -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects (same as AllObjects)
echo "musicdiff -i decoratednotesandrests otherobjects"
python -m musicdiff -o t -i decoratednotesandrests otherobjects -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, no Lyrics
echo "musicdiff -i decoratednotesandrests otherobjects -x lyrics"
python -m musicdiff -o t -i decoratednotesandrests otherobjects -x lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, no Lyrics, no Barlines
echo "musicdiff -i decoratednotesandrests otherobjects -x lyrics barlines"
python -m musicdiff -o t -i decoratednotesandrests otherobjects -x lyrics barlines -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# AllObjects (same as DecoratedNotesAndRests, OtherObjects)
echo "musicdiff -i allobjects"
python -m musicdiff -o t -i allobjects -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, Style
echo "musicdiff -i decoratednotesandrests otherobjects style"
python -m musicdiff -o t -i decoratednotesandrests otherobjects style -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# DecoratedNotesAndRests, OtherObjects, Style, no Lyrics
echo "musicdiff -i decoratednotesandrests otherobjects style -x lyrics"
python -m musicdiff -o t -i decoratednotesandrests otherobjects style -x lyrics -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# AllObjects | Style (same as DecoratedNotesAndRests, OtherObjects, Style)
echo "musicdiff -i allobjects style"
python -m musicdiff -o t -i allobjects style -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# Metadata only
echo "musicdiff -i metadata"
python -m musicdiff -o t -i metadata -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

# Everything except Voicing
echo "musicdiff -i allobjects style metadata"
python -m musicdiff -o t -i allobjects style metadata -- tests/test_scores/test_all_details_1a.mei tests/test_scores/test_all_details_1b.mei

print Total failures: ${fails}
exit ${fails}
